// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: protobuf/internalapi/analytics.proto

package internalapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonthlyActiveUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DaoId string `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
}

func (x *MonthlyActiveUsersRequest) Reset() {
	*x = MonthlyActiveUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonthlyActiveUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyActiveUsersRequest) ProtoMessage() {}

func (x *MonthlyActiveUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyActiveUsersRequest.ProtoReflect.Descriptor instead.
func (*MonthlyActiveUsersRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *MonthlyActiveUsersRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

type MonthlyActiveUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeriodStarted  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=period_started,json=periodStarted,proto3" json:"period_started,omitempty"`
	ActiveUsers    uint64                 `protobuf:"varint,2,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	NewActiveUsers uint64                 `protobuf:"varint,3,opt,name=new_active_users,json=newActiveUsers,proto3" json:"new_active_users,omitempty"`
}

func (x *MonthlyActiveUsers) Reset() {
	*x = MonthlyActiveUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonthlyActiveUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyActiveUsers) ProtoMessage() {}

func (x *MonthlyActiveUsers) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyActiveUsers.ProtoReflect.Descriptor instead.
func (*MonthlyActiveUsers) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *MonthlyActiveUsers) GetPeriodStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStarted
	}
	return nil
}

func (x *MonthlyActiveUsers) GetActiveUsers() uint64 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *MonthlyActiveUsers) GetNewActiveUsers() uint64 {
	if x != nil {
		return x.NewActiveUsers
	}
	return 0
}

type MonthlyActiveUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MonthlyActiveUsers []*MonthlyActiveUsers `protobuf:"bytes,1,rep,name=monthly_active_users,json=monthlyActiveUsers,proto3" json:"monthly_active_users,omitempty"`
}

func (x *MonthlyActiveUsersResponse) Reset() {
	*x = MonthlyActiveUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonthlyActiveUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyActiveUsersResponse) ProtoMessage() {}

func (x *MonthlyActiveUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyActiveUsersResponse.ProtoReflect.Descriptor instead.
func (*MonthlyActiveUsersResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *MonthlyActiveUsersResponse) GetMonthlyActiveUsers() []*MonthlyActiveUsers {
	if x != nil {
		return x.MonthlyActiveUsers
	}
	return nil
}

type VoterBucketsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DaoId string `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
}

func (x *VoterBucketsRequest) Reset() {
	*x = VoterBucketsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoterBucketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoterBucketsRequest) ProtoMessage() {}

func (x *VoterBucketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoterBucketsRequest.ProtoReflect.Descriptor instead.
func (*VoterBucketsRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *VoterBucketsRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

type VoterBucketsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []*VoterGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *VoterBucketsResponse) Reset() {
	*x = VoterBucketsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoterBucketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoterBucketsResponse) ProtoMessage() {}

func (x *VoterBucketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoterBucketsResponse.ProtoReflect.Descriptor instead.
func (*VoterBucketsResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *VoterBucketsResponse) GetGroups() []*VoterGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type VoterGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Votes  string `protobuf:"bytes,1,opt,name=votes,proto3" json:"votes,omitempty"`
	Voters uint64 `protobuf:"varint,2,opt,name=voters,proto3" json:"voters,omitempty"`
}

func (x *VoterGroup) Reset() {
	*x = VoterGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoterGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoterGroup) ProtoMessage() {}

func (x *VoterGroup) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoterGroup.ProtoReflect.Descriptor instead.
func (*VoterGroup) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *VoterGroup) GetVotes() string {
	if x != nil {
		return x.Votes
	}
	return ""
}

func (x *VoterGroup) GetVoters() uint64 {
	if x != nil {
		return x.Voters
	}
	return 0
}

type ExclusiveVotersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DaoId string `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
}

func (x *ExclusiveVotersRequest) Reset() {
	*x = ExclusiveVotersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExclusiveVotersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExclusiveVotersRequest) ProtoMessage() {}

func (x *ExclusiveVotersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExclusiveVotersRequest.ProtoReflect.Descriptor instead.
func (*ExclusiveVotersRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *ExclusiveVotersRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

type ExclusiveVotersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count   uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Percent uint32 `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"`
}

func (x *ExclusiveVotersResponse) Reset() {
	*x = ExclusiveVotersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExclusiveVotersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExclusiveVotersResponse) ProtoMessage() {}

func (x *ExclusiveVotersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExclusiveVotersResponse.ProtoReflect.Descriptor instead.
func (*ExclusiveVotersResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *ExclusiveVotersResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ExclusiveVotersResponse) GetPercent() uint32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type MonthlyNewProposalsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DaoId string `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
}

func (x *MonthlyNewProposalsRequest) Reset() {
	*x = MonthlyNewProposalsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonthlyNewProposalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyNewProposalsRequest) ProtoMessage() {}

func (x *MonthlyNewProposalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyNewProposalsRequest.ProtoReflect.Descriptor instead.
func (*MonthlyNewProposalsRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *MonthlyNewProposalsRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

type ProposalsByMonth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeriodStarted  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=period_started,json=periodStarted,proto3" json:"period_started,omitempty"`
	ProposalsCount uint64                 `protobuf:"varint,2,opt,name=proposals_count,json=proposalsCount,proto3" json:"proposals_count,omitempty"`
}

func (x *ProposalsByMonth) Reset() {
	*x = ProposalsByMonth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalsByMonth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalsByMonth) ProtoMessage() {}

func (x *ProposalsByMonth) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalsByMonth.ProtoReflect.Descriptor instead.
func (*ProposalsByMonth) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *ProposalsByMonth) GetPeriodStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStarted
	}
	return nil
}

func (x *ProposalsByMonth) GetProposalsCount() uint64 {
	if x != nil {
		return x.ProposalsCount
	}
	return 0
}

type MonthlyNewProposalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProposalsByMonth []*ProposalsByMonth `protobuf:"bytes,1,rep,name=proposals_by_month,json=proposalsByMonth,proto3" json:"proposals_by_month,omitempty"`
}

func (x *MonthlyNewProposalsResponse) Reset() {
	*x = MonthlyNewProposalsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonthlyNewProposalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyNewProposalsResponse) ProtoMessage() {}

func (x *MonthlyNewProposalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyNewProposalsResponse.ProtoReflect.Descriptor instead.
func (*MonthlyNewProposalsResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *MonthlyNewProposalsResponse) GetProposalsByMonth() []*ProposalsByMonth {
	if x != nil {
		return x.ProposalsByMonth
	}
	return nil
}

type PercentSucceededProposalsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DaoId string `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
}

func (x *PercentSucceededProposalsRequest) Reset() {
	*x = PercentSucceededProposalsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PercentSucceededProposalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PercentSucceededProposalsRequest) ProtoMessage() {}

func (x *PercentSucceededProposalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PercentSucceededProposalsRequest.ProtoReflect.Descriptor instead.
func (*PercentSucceededProposalsRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *PercentSucceededProposalsRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

type PercentSucceededProposalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Percent uint32 `protobuf:"varint,1,opt,name=percent,proto3" json:"percent,omitempty"`
}

func (x *PercentSucceededProposalsResponse) Reset() {
	*x = PercentSucceededProposalsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_internalapi_analytics_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PercentSucceededProposalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PercentSucceededProposalsResponse) ProtoMessage() {}

func (x *PercentSucceededProposalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_internalapi_analytics_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PercentSucceededProposalsResponse.ProtoReflect.Descriptor instead.
func (*PercentSucceededProposalsResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_internalapi_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *PercentSucceededProposalsResponse) GetPercent() uint32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

var File_protobuf_internalapi_analytics_proto protoreflect.FileDescriptor

var file_protobuf_internalapi_analytics_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x19, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x61, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x64, 0x61, 0x6f, 0x49, 0x64, 0x22, 0xa4, 0x01, 0x0a, 0x12, 0x4d, 0x6f, 0x6e,
	0x74, 0x68, 0x6c, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12,
	0x41, 0x0a, 0x0e, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0d, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x6e, 0x65, 0x77, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0e, 0x6e, 0x65, 0x77, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x22,
	0x6f, 0x0a, 0x1a, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a,
	0x14, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c,
	0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x12, 0x6d, 0x6f,
	0x6e, 0x74, 0x68, 0x6c, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x22, 0x2c, 0x0a, 0x13, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x61, 0x6f, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x6f, 0x49, 0x64, 0x22, 0x47,
	0x0a, 0x14, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x3a, 0x0a, 0x0a, 0x56, 0x6f, 0x74, 0x65, 0x72,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x6f, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x76, 0x6f, 0x74,
	0x65, 0x72, 0x73, 0x22, 0x2f, 0x0a, 0x16, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65,
	0x56, 0x6f, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x64, 0x61, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64,
	0x61, 0x6f, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x17, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76,
	0x65, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x22,
	0x33, 0x0a, 0x1a, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x64, 0x61, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64,
	0x61, 0x6f, 0x49, 0x64, 0x22, 0x7e, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c,
	0x73, 0x42, 0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x41, 0x0a, 0x0e, 0x70, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x70, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x70,
	0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6a, 0x0a, 0x1b, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x4e,
	0x65, 0x77, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73,
	0x5f, 0x62, 0x79, 0x5f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x10,
	0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68,
	0x22, 0x39, 0x0a, 0x20, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x65, 0x64, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x61, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x6f, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x21, 0x50,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x50,
	0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x32, 0x9a, 0x04, 0x0a, 0x09, 0x41,
	0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x12, 0x68, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d,
	0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x26, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x56, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x20, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x73,
	0x12, 0x23, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x45,
	0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x61, 0x70, 0x69, 0x2e, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x56, 0x6f, 0x74,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x70,
	0x6f, 0x73, 0x61, 0x6c, 0x73, 0x12, 0x27, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x4e, 0x65, 0x77, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x6e,
	0x74, 0x68, 0x6c, 0x79, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7d, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x50,
	0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x12, 0x2d, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_internalapi_analytics_proto_rawDescOnce sync.Once
	file_protobuf_internalapi_analytics_proto_rawDescData = file_protobuf_internalapi_analytics_proto_rawDesc
)

func file_protobuf_internalapi_analytics_proto_rawDescGZIP() []byte {
	file_protobuf_internalapi_analytics_proto_rawDescOnce.Do(func() {
		file_protobuf_internalapi_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_internalapi_analytics_proto_rawDescData)
	})
	return file_protobuf_internalapi_analytics_proto_rawDescData
}

var file_protobuf_internalapi_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protobuf_internalapi_analytics_proto_goTypes = []interface{}{
	(*MonthlyActiveUsersRequest)(nil),         // 0: internalapi.MonthlyActiveUsersRequest
	(*MonthlyActiveUsers)(nil),                // 1: internalapi.MonthlyActiveUsers
	(*MonthlyActiveUsersResponse)(nil),        // 2: internalapi.MonthlyActiveUsersResponse
	(*VoterBucketsRequest)(nil),               // 3: internalapi.VoterBucketsRequest
	(*VoterBucketsResponse)(nil),              // 4: internalapi.VoterBucketsResponse
	(*VoterGroup)(nil),                        // 5: internalapi.VoterGroup
	(*ExclusiveVotersRequest)(nil),            // 6: internalapi.ExclusiveVotersRequest
	(*ExclusiveVotersResponse)(nil),           // 7: internalapi.ExclusiveVotersResponse
	(*MonthlyNewProposalsRequest)(nil),        // 8: internalapi.MonthlyNewProposalsRequest
	(*ProposalsByMonth)(nil),                  // 9: internalapi.ProposalsByMonth
	(*MonthlyNewProposalsResponse)(nil),       // 10: internalapi.MonthlyNewProposalsResponse
	(*PercentSucceededProposalsRequest)(nil),  // 11: internalapi.PercentSucceededProposalsRequest
	(*PercentSucceededProposalsResponse)(nil), // 12: internalapi.PercentSucceededProposalsResponse
	(*timestamppb.Timestamp)(nil),             // 13: google.protobuf.Timestamp
}
var file_protobuf_internalapi_analytics_proto_depIdxs = []int32{
	13, // 0: internalapi.MonthlyActiveUsers.period_started:type_name -> google.protobuf.Timestamp
	1,  // 1: internalapi.MonthlyActiveUsersResponse.monthly_active_users:type_name -> internalapi.MonthlyActiveUsers
	5,  // 2: internalapi.VoterBucketsResponse.groups:type_name -> internalapi.VoterGroup
	13, // 3: internalapi.ProposalsByMonth.period_started:type_name -> google.protobuf.Timestamp
	9,  // 4: internalapi.MonthlyNewProposalsResponse.proposals_by_month:type_name -> internalapi.ProposalsByMonth
	0,  // 5: internalapi.Analytics.GetMonthlyActiveUsers:input_type -> internalapi.MonthlyActiveUsersRequest
	3,  // 6: internalapi.Analytics.GetVoterBuckets:input_type -> internalapi.VoterBucketsRequest
	6,  // 7: internalapi.Analytics.GetExclusiveVoters:input_type -> internalapi.ExclusiveVotersRequest
	8,  // 8: internalapi.Analytics.GetMonthlyNewProposals:input_type -> internalapi.MonthlyNewProposalsRequest
	11, // 9: internalapi.Analytics.GetPercentSucceededProposals:input_type -> internalapi.PercentSucceededProposalsRequest
	2,  // 10: internalapi.Analytics.GetMonthlyActiveUsers:output_type -> internalapi.MonthlyActiveUsersResponse
	4,  // 11: internalapi.Analytics.GetVoterBuckets:output_type -> internalapi.VoterBucketsResponse
	7,  // 12: internalapi.Analytics.GetExclusiveVoters:output_type -> internalapi.ExclusiveVotersResponse
	10, // 13: internalapi.Analytics.GetMonthlyNewProposals:output_type -> internalapi.MonthlyNewProposalsResponse
	12, // 14: internalapi.Analytics.GetPercentSucceededProposals:output_type -> internalapi.PercentSucceededProposalsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protobuf_internalapi_analytics_proto_init() }
func file_protobuf_internalapi_analytics_proto_init() {
	if File_protobuf_internalapi_analytics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_internalapi_analytics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonthlyActiveUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_internalapi_analytics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonthlyActiveUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_internalapi_analytics_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonthlyActiveUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_internalapi_analytics_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoterBucketsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_internalapi_analytics_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoterBucketsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_internalapi_analytics_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoterGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_internalapi_analytics_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExclusiveVotersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_internalapi_analytics_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExclusiveVotersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_internalapi_analytics_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonthlyNewProposalsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_internalapi_analytics_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalsByMonth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_internalapi_analytics_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonthlyNewProposalsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_internalapi_analytics_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PercentSucceededProposalsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_internalapi_analytics_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PercentSucceededProposalsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_internalapi_analytics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_internalapi_analytics_proto_goTypes,
		DependencyIndexes: file_protobuf_internalapi_analytics_proto_depIdxs,
		MessageInfos:      file_protobuf_internalapi_analytics_proto_msgTypes,
	}.Build()
	File_protobuf_internalapi_analytics_proto = out.File
	file_protobuf_internalapi_analytics_proto_rawDesc = nil
	file_protobuf_internalapi_analytics_proto_goTypes = nil
	file_protobuf_internalapi_analytics_proto_depIdxs = nil
}
